function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-May-2014 18:35:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on');
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1e-16 0.01]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = plot(X1,YMatrix1,'Parent',axes1);
set(semilogy1(1),'DisplayName','5');
set(semilogy1(2),'DisplayName','10');
set(semilogy1(3),'DisplayName','15');
set(semilogy1(4),'DisplayName','20');
set(semilogy1(5),'DisplayName','25');

% Create ylabel
ylabel('Absolute interpolatiefout','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.173905367231638 0.723411171471476 0.0416666666666667 0.17753120665742],...
    'FontSize',14);

